#pragma once
#include"AddANDgate2.h"
#include"AddORgate2.h"
#include"AddNANDgate2.h"
#include"AddNORgate2.h"
#include"AddXORgate2.h"
#include"AddXNORgate2.h"
#include"AddXORgate3.h"
#include"AddANDgate3.h"
#include"AddNORgate3.h"
#include"AddINVgate.h"
#include"AddBUFFgate.h"
#include"AddLed.h"
#include"AddSwitch.h"
#include"Label.h"
#include"Edit.h"
#include"Connect.h"
#include"Delete.h"
#include "Actions\Copy.h"
#include "Actions\Paste.h"
#include "Actions\CutA.h"
#include "Actions\Save.h"
#include "Actions\Load.h"
#include "Simulate.h"
#include "Probe.h"
#include "CreateTT.h"